# Generated by Django 3.2.5 on 2021-09-25 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('stock_exchange', models.CharField(blank=True, max_length=50)),
                ('ticker', models.CharField(blank=True, max_length=12)),
                ('price', models.FloatField(default=0)),
                ('price_history', models.JSONField(blank=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('website', models.CharField(blank=True, max_length=50)),
                ('xing_profile', models.CharField(blank=True, max_length=50)),
                ('kununu_profile', models.CharField(blank=True, max_length=50)),
                ('kununu_score', models.FloatField(default=0)),
                ('industry', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_price', models.FloatField(default=0)),
                ('bought_before', models.BooleanField(default=False)),
                ('currently_holding', models.BooleanField(default=True)),
                ('last_buy_date', models.DateTimeField(blank=True)),
                ('last_sell_date', models.DateTimeField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.portfolio')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='companies',
            field=models.ManyToManyField(through='app.PortfolioCompany', to='app.Company'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
