# Generated by Django 3.2.5 on 2021-09-25 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210925_0758'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='portfoliocompany',
            table='app_portfolio_company',
        ),
    ]
