# Generated by Django 3.2.5 on 2021-09-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_portfoliocompany_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='kununu_score',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='price_history',
            field=models.JSONField(blank=True, default=0),
        ),
    ]
