# Generated by Django 3.2.5 on 2021-10-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211023_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='future_endeavours',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='company',
            name='revenue_drive',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
