# Generated by Django 3.2.5 on 2022-04-01 09:17

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211030_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=7)),
                ('background', models.CharField(max_length=3000)),
                ('question', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=3)),
                ('closing_price', models.JSONField(default=app.models.placeholder_dict)),
                ('average_forecast', models.JSONField(default=app.models.placeholder_dict)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='price_history',
            field=models.JSONField(blank=True, default=app.models.placeholder_dict),
        ),
    ]
