# Generated by Django 3.2.5 on 2022-04-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_title_challenge_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='days_in_month',
            field=models.IntegerField(default=0),
        ),
    ]
